<p>(a) Upon arrival, ADC will execute the Delivery Acceptance document in the form of Appendix D of this Agreement confirming the safe delivery, acceptance of the Equipment by ADC, and commencement of the associated Work Scope.</p>
<p>(b) ADC will provide the following Services as outlined in Appendix C to facilitate the disassembly of the Equipment:</p>
<ol class="decimal">
    <li>All Services and activities will be provided during the hours of 8:00a to 5:00p local.  Any requests or Additional Services will be billed at a overtime rate in accordance with Appendix B.</li>
    <li>ADC shall provide labor to disassemble, package and crate the Components removed under the Work Scope in Appendix C.</li>
    <li>ADC will defuel or arrange to have defueled the Aircraft at the rate set forth in Appendix B, and will dispose of fuel in accordance with appropriate respect Facility airport authority disposition regulations. ADC bears sole responsibility and liability for compliance with same. ADC will ensure that such defueling will be conducted in compliance with applicable law, and ADC will upon such defueling, and without further act, take title to all such fuel removed.</li>
    <li>All removed Components will be reasonably cleaned, enabling identification by manufacturer’s data plate.</li>
    <li>ADC will immediately attach an Removal Tag to each component as it is removed from the Equipment, which Removal Tag will be in the form of Appendix 1.</li>
    <li>All parts that are without a manufacturer’s data plate or legible part number or serial number will be identified by the Illustrated Parts Catalog (“IPC”) and tagged by an authorized A&P mechanic.</li>
    <li>Following such positive identification by the A&amp;P mechanic, ADC will enter the part number and serial number on a Receiving Report in the form of Exhibit 2 (the “Receiving Report”).</li>
    <li>If Customer does not supply current aircraft specific IPC, ADC is not responsible for the accuracy of the part identification resulting from the use of a generic IPC.</li>
    <li>All Components will be removed at the assembly level.</li>
    <li>Any requests for further disassembly to a sub-assembly level will be performed as an Additional Service.</li>
    <li>Specialized disassembly equipment and tooling not included in the Total Price set forth in Appendix B unless otherwise noted and agreed upon.</li>
    <li>If Customer requires the gear removed before the completion of the Work Scope, Customer will be responsible for providing replacement gear for continued movement and disassembly of the Equipment. Installation of replacement gear is not included in the Total Price and will be accomplished on a time and material basis (If applicable).</li>
    <li>Pursuant to FAR 43.10, FAR 91.417, and FAR 91.419, all life limited parts will be quarantined upon removal from the Equipment until Customer provides FAR-required information. All parts placed in Quarantine are subject to monthly storage fees. For any parts left in Quarantine storage longer than 3 months (90 days), the Customer hereby grants ADC explicit permission to destroy such parts.</li>
    <li>Any services over and above the Work Scope as defined in Appendix C shall be governed by the Additional Services fees in Appendix B.</li>
    <li>Following the completion of the Work Scope, Customer shall be responsible for the shipment of all removed components from the Facility. Customer shall bear all risk and expense of transporting the removed components from Facility. ADC shall supply the weights & dimensions for shipping, along with packing list for each shipment.</li>
    <li>Customer shall ship the material from ADC’s facility within 10 business days of completion notification by ADC.   Failure to ship all material within two weeks of notice from ADC stating that all the material that is available to be shipped, will result in a warehouse fee for the material at a monthly storage rate set forth in Appendix B.</li>
    <li>Customer may request component removal and shipping before the disassembly is completed.  ADC will honor requests based on time and availability and will be charged a per shipment fee in accordance with Appendix B.  Urgent requests and AOG mandatory removals can be completed as an Additional Service billed at the hourly rates outlined accordingly.  AOG shipments will be charged an AOG fee in accordance with Appendix B (special crating for freight trucking will be on a part basis, and written approval required).</li>
</ol>
