<p>(a)	ADC shall, at all times while the Equipment is in its possession, custody or control pursuant to the Agreement, maintain in full force and effect policies of workmen’s compensation insurance coverage as required by law and general liability insurance, including property insurance for ADC’s facility, and shall be issued by responsible carriers.  The insurance policies referred to in this Article shall provide that they may not be canceled unless at least thirty (30) days prior written notice of such cancellation is provided to Customer.</p>
<p>(b)	Customer shall maintain property insurance for the Equipment and associated removed parts.</p>
<p>(c)	ADC is not responsible for the condition of the components as they’ve arrived on the aircraft at the time of removal.</p>
<p>(d)	Each Party agrees to defend, indemnify and hold harm less the other Party, its officers, servants, agents, and employees from and against all losses, damages, claims, injury to or death of persons, including employees of Customer and ADC (except for Injuries to and death of employees of ADC that are covered by workers compensation insurance) and loss of or damage to property of either Party or any third parties, arising out of or in any manner connected with the Work Scope or Additional Services performed by ADC pursuant to this Agreement, except in the limited instance where loss or damage results from the gross negligence or willful misconduct of the offending Party.</p>
<p>(e)	In order to fully protect its own Interests and to provide the indemnity to ADC specified above, Customer warrants and represents to ADC that it has insurance policies in full force and effect for the inclusive time that Aircraft will be at the Facility.</p>
<p>(f)	Customer shall furnish to ADC prior to the commencement of any work on the Aircraft, certificates of insurance evidencing the following:</p>
<ol class="lower-alpha">
    <li>Aviation General Liability Insurance, including contractual liability Insuring the indemnity agreement set forth in Article 11 above, with a combined single limit of not less than one million dollars (US$1,000,000.00);</li>
    <li>All Risks Property insurance in an amount equal to the full replacement value of each Equipment.</li>
</ol>
<p>(g)	ADC warrants and represents to Customer that it has Insurance policies in full force and effect for the Inclusive time that Aircraft will be at the Facility.  Upon Customer's request, ADC shall furnish to Customer a certificate of Insurance evidencing Comprehensive General Aviation Liability Insurance, including Premises Automotive liability, Premises, Products and Completed Operations Liabilities, Hangar keepers Liability, and contractual liability Insuring the Indemnity agreement set forth above, with a combined single limit Bodily Injury and Property Damage of not less than five million dollars (US$5,000,000.00) for any one occurrence (in the annual aggregate in respect to Products and Completed Operations Liability).</p>
<p>(h) The policies referred to in this Article shall provide that they may not be canceled or materially altered unless at least thirty (30) days prior written notice of such cancellation or alteration is provided to ADC with respect to the Insurance referred to in Article above.</p>
